ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: MeesuMaes/coai
DockerComposeEnvPath: .env
RegionId: ap-southeast-1
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yaml
Owner: MeesuMaes
Branch: main
Platform: github
